config/routes.rb
Rails.application.routes.draw do
 resources :lists

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = list.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @lists = List.new
  end

  def create
    @list.save
    redirect_to lists_path
  else 
    render: new
  end
end

private

def list_params
  params.require(:post).permit(:body)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1> Lists </h1>
<p><%= link_to 'New List', new_list_path %></p>
<% @lists.each do |list| %>
<p><%= list.body %></p>
<%= link_to 'Show list', list_path(list) 
% end % 

app/views/lists/new.html.erb
<h1> New List </h1>
<%= form_for @list do |f| %>
<%= f.label :body %>
<%= f.text_field :body %>
<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1> List </h1>
<p><%= @list.body %></p>
<%= link_to 'Back', lists_path %>